using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;

public struct VisualizerAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public VisualizerAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public VisualizerAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var localTransformLookup = state.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var postTransformMatrixLookup = state.GetComponentLookup<PostTransformMatrix>(isReadOnly: false);
        var materialPropertyTextureTilingLookup = state.GetComponentLookup<MaterialPropertyTextureTiling>(isReadOnly: false);
        LocalTransformRW = localTransformLookup.GetRefRW(entity);
        PostTransformMatrixRW = postTransformMatrixLookup.HasComponent(entity) ? postTransformMatrixLookup.GetRefRW(entity) : default;
        MaterialPropertyTextureTilingRW = materialPropertyTextureTilingLookup.HasComponent(entity) ? materialPropertyTextureTilingLookup.GetRefRW(entity) : default;
    }

    /// SystemBase / managed system variant.
    public VisualizerAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var localTransformLookup = system.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var postTransformMatrixLookup = system.GetComponentLookup<PostTransformMatrix>(isReadOnly: false);
        var materialPropertyTextureTilingLookup = system.GetComponentLookup<MaterialPropertyTextureTiling>(isReadOnly: false);
        LocalTransformRW = localTransformLookup.GetRefRW(entity);
        PostTransformMatrixRW = postTransformMatrixLookup.HasComponent(entity) ? postTransformMatrixLookup.GetRefRW(entity) : default;
        MaterialPropertyTextureTilingRW = materialPropertyTextureTilingLookup.HasComponent(entity) ? materialPropertyTextureTilingLookup.GetRefRW(entity) : default;
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new VisualizerAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public VisualizerAspect Set(LookupSlot<LocalTransform> slot)
    {
        LocalTransformRW = slot.BindRW(Entity);
        return this;
    }

    public VisualizerAspect Set(LookupSlot<PostTransformMatrix> slot)
    {
        PostTransformMatrixRW = slot.BindRWOptional(Entity);
        return this;
    }

    public VisualizerAspect Set(LookupSlot<MaterialPropertyTextureTiling> slot)
    {
        MaterialPropertyTextureTilingRW = slot.BindRWOptional(Entity);
        return this;
    }

    public VisualizerAspect Set(ComponentLookup<LocalTransform> lookup)
    {
        LocalTransformRW = lookup.GetRefRW(Entity);
        return this;
    }

    public VisualizerAspect Set(ComponentLookup<PostTransformMatrix> lookup)
    {
        PostTransformMatrixRW = lookup.GetRefRW(Entity);
        return this;
    }

    public VisualizerAspect Set(ComponentLookup<MaterialPropertyTextureTiling> lookup)
    {
        MaterialPropertyTextureTilingRW = lookup.GetRefRW(Entity);
        return this;
    }

    // From IJobEntity Execute parameters.
    public VisualizerAspect Set(RefRW<LocalTransform> value)
    {
        LocalTransformRW = value;
        return this;
    }
    public VisualizerAspect Set(RefRW<PostTransformMatrix> value)
    {
        PostTransformMatrixRW = value;
        return this;
    }
    public VisualizerAspect Set(RefRW<MaterialPropertyTextureTiling> value)
    {
        MaterialPropertyTextureTilingRW = value;
        return this;
    }
    #endregion </auto-generated-lookup>
    
    public Entity Entity;
    public RefRW<LocalTransform> LocalTransformRW;
    [OptionalLookup] public RefRW<PostTransformMatrix> PostTransformMatrixRW;
    [OptionalLookup] public RefRW<MaterialPropertyTextureTiling> MaterialPropertyTextureTilingRW;

    public void SetTextureTiling(float x, float y = 1)
    {
        MaterialPropertyTextureTilingRW.ValueRW.Value = new float2(x, y);
    }

    public void SetPositionRotation(float3 position, quaternion rotation)
    {
        LocalTransformRW.ValueRW = LocalTransform.FromPositionRotation(position, rotation);
    }

    public void SetNonUniformScale(float x, float y, float z)
    {
        PostTransformMatrixRW.ValueRW.Value = float4x4.Scale(x, y, z);
    }
}