using Unity.Entities;
using Unity.Mathematics;

public struct RoadLaneData : IComponentData
{
    public RoadPortEnt StartPortEnt, EndPortEnt;
    public RoadSegmentEnt Parent;
    public RoadLaneEnt LeftNeighbour, RightNeighbour;
    public float LaneWidth;
}

public struct RoadLanePoint : IBufferElementData
{
    public float3 Position;
    public float Distance;
}

public struct RoadLaneUpdatePoints : IComponentData, IEnableableComponent { }

public struct RoadLaneAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    public struct Lookup
    {
        public LookupSlot<RoadLaneData> RoadLaneDataLookup;
        public BufferSlot<RoadLanePoint> RoadLanePointLookup;
        public EnableableSlot<RoadLaneUpdatePoints> RoadLaneUpdatePointsLookupEnabledRefRW;
        public void Initialize(ref SystemState state)
        {
            RoadLaneDataLookup.Initialize(ref state);
            RoadLanePointLookup.Initialize(ref state);
            RoadLaneUpdatePointsLookupEnabledRefRW.Initialize(ref state);
        }
        /// SystemBase / managed system variant.
        public void Initialize(ComponentSystemBase system)
        {
            RoadLaneDataLookup.Initialize(system);
            RoadLanePointLookup.Initialize(system);
            RoadLaneUpdatePointsLookupEnabledRefRW.Initialize(system);
        }
        public void Update(ref SystemState state)
        {
            RoadLaneDataLookup.Update(ref state);
            RoadLanePointLookup.Update(ref state);
            RoadLaneUpdatePointsLookupEnabledRefRW.Update(ref state);
        }
        public void Update(SystemBase system)
        {
            RoadLaneDataLookup.Update(system);
            RoadLanePointLookup.Update(system);
            RoadLaneUpdatePointsLookupEnabledRefRW.Update(system);
        }
        public RoadLaneAspect this[Entity e] => new RoadLaneAspect
        {
            Entity = e,
            Data = RoadLaneDataLookup.BindRW(e),
            Points = RoadLanePointLookup.Bind(e),
            UpdatePoints = RoadLaneUpdatePointsLookupEnabledRefRW.BindRW(e)
        };
    }

    /// Main-thread construction without a cached Lookup: builds
    /// temporary lookups for this entity. Not usable inside jobs.
    /// (EntityManager cannot return RefRO/RefRW for an entity.)
    public RoadLaneAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = state.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        var roadLanePointLookup = state.GetBufferLookup<RoadLanePoint>(isReadOnly: false);
        var roadLaneUpdatePointsLookupEnabledRefRW = state.GetComponentLookup<RoadLaneUpdatePoints>(isReadOnly: false);
        Data = roadLaneDataLookup.GetRefRW(entity);
        Points = roadLanePointLookup[entity];
        UpdatePoints = roadLaneUpdatePointsLookupEnabledRefRW.GetEnabledRefRW<RoadLaneUpdatePoints>(entity);
    }

    /// SystemBase / managed system variant.
    public RoadLaneAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = system.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        var roadLanePointLookup = system.GetBufferLookup<RoadLanePoint>(isReadOnly: false);
        var roadLaneUpdatePointsLookupEnabledRefRW = system.GetComponentLookup<RoadLaneUpdatePoints>(isReadOnly: false);
        Data = roadLaneDataLookup.GetRefRW(entity);
        Points = roadLanePointLookup[entity];
        UpdatePoints = roadLaneUpdatePointsLookupEnabledRefRW.GetEnabledRefRW<RoadLaneUpdatePoints>(entity);
    }

    /// Builds the aspect from IJobEntity Execute parameters — no
    /// Lookup needed. Pass default for fields this job does not
    /// iterate; unbound fields simply read as invalid. Tolerant
    /// (AspectRef) fields take an RO and an RW parameter: pass just
    /// the RW one for full read+write, or just the RO one for reads.
    public static RoadLaneAspect Create(Entity entity,
        RefRW<RoadLaneData> data = default,
        DynamicBuffer<RoadLanePoint> points = default,
        EnabledRefRW<RoadLaneUpdatePoints> updatePoints = default)
    {
        return new RoadLaneAspect
        {
            Entity = entity,
            Data = data,
            Points = points,
            UpdatePoints = updatePoints
        };
    }
    #endregion </auto-generated-lookup>
   
    public Entity Entity;
    public RefRW<RoadLaneData> Data;
    public DynamicBuffer<RoadLanePoint> Points;
    public EnabledRefRW<RoadLaneUpdatePoints> UpdatePoints;

    public void SetParent(RoadSegmentEnt roadSegmentEnt) => Data.ValueRW.Parent = roadSegmentEnt;
    public void SetStartPort(RoadPortEnt roadPortEnt) => Data.ValueRW.StartPortEnt = roadPortEnt;
    public void SetEndPort(RoadPortEnt roadPortEnt) => Data.ValueRW.EndPortEnt = roadPortEnt;
    public void SetLaneWidth(float laneWidth) => Data.ValueRW.LaneWidth = laneWidth;
}