using Unity.Entities;

public struct RoadLaneData : IComponentData
{
    public RoadPortEnt StartPortEnt, EndPortEnt;
    public RoadSegmentEnt Parent;
    public RoadLaneEnt LeftNeighbour, RightNeighbour;
    public float LaneWidth;
}

public struct RoadLaneAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    public struct Lookup
    {
        public LookupSlot<RoadLaneData> RoadLaneDataLookup;
        public void Initialize(ref SystemState state)
        {
            RoadLaneDataLookup.Initialize(ref state);
        }
        /// SystemBase / managed system variant.
        public void Initialize(ComponentSystemBase system)
        {
            RoadLaneDataLookup.Initialize(system);
        }
        public void Update(ref SystemState state)
        {
            RoadLaneDataLookup.Update(ref state);
        }
        public void Update(SystemBase system)
        {
            RoadLaneDataLookup.Update(system);
        }
        public RoadLaneAspect this[Entity e] => new RoadLaneAspect
        {
            Entity = e,
            Data = RoadLaneDataLookup.BindRW(e)
        };
    }

    /// Main-thread construction without a cached Lookup: builds
    /// temporary lookups for this entity. Not usable inside jobs.
    /// (EntityManager cannot return RefRO/RefRW for an entity.)
    public RoadLaneAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = state.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        Data = roadLaneDataLookup.GetRefRW(entity);
    }

    /// SystemBase / managed system variant.
    public RoadLaneAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = system.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        Data = roadLaneDataLookup.GetRefRW(entity);
    }
    #endregion </auto-generated-lookup>

    public Entity Entity;
    public RefRW<RoadLaneData> Data;

    public void SetParent(RoadSegmentEnt roadSegmentEnt) => Data.ValueRW.Parent = roadSegmentEnt;
    public void SetStartPort(RoadPortEnt roadPortEnt) => Data.ValueRW.StartPortEnt = roadPortEnt;
    public void SetEndPort(RoadPortEnt roadPortEnt) => Data.ValueRW.EndPortEnt = roadPortEnt;
    public void SetLaneWidth(float laneWidth) => Data.ValueRW.LaneWidth = laneWidth;
}