using Unity.Entities;
using Unity.Mathematics;

public struct RoadLaneData : IComponentData
{
    public RoadPortEnt StartPortEnt, EndPortEnt;
    public RoadSegmentEnt Parent;
    public float LaneWidth;
}

public struct RoadLanePoint : IBufferElementData
{
    public float3 Position;
    public float Distance;
}
public struct RoadLaneNeighbour : IBufferElementData
{
    public RoadLaneEnt Entity;
    public bool TheSameDirection;
}


public struct RoadLaneUpdatePoints : IComponentData, IEnableableComponent { }
public struct RoadLaneUpdateNeighbours : IComponentData, IEnableableComponent { }


public struct RoadLaneAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public RoadLaneAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public RoadLaneAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = state.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        var roadLanePointLookup = state.GetBufferLookup<RoadLanePoint>(isReadOnly: false);
        var roadLaneNeighbourLookup = state.GetBufferLookup<RoadLaneNeighbour>(isReadOnly: false);
        var roadLaneUpdatePointsLookupAspectEnabledRef = state.GetComponentLookup<RoadLaneUpdatePoints>(isReadOnly: false);
        var roadLaneUpdateNeighboursLookupAspectEnabledRef = state.GetComponentLookup<RoadLaneUpdateNeighbours>(isReadOnly: false);
        Data = new AspectRef<RoadLaneData>(roadLaneDataLookup, entity, isReadOnly: false);
        Points = roadLanePointLookup[entity];
        Neighbours = roadLaneNeighbourLookup[entity];
        UpdatePoints = new AspectEnabledRef<RoadLaneUpdatePoints>(roadLaneUpdatePointsLookupAspectEnabledRef, entity, isReadOnly: false);
        UpdateNeighbours = new AspectEnabledRef<RoadLaneUpdateNeighbours>(roadLaneUpdateNeighboursLookupAspectEnabledRef, entity, isReadOnly: false);
    }

    /// SystemBase / managed system variant.
    public RoadLaneAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadLaneDataLookup = system.GetComponentLookup<RoadLaneData>(isReadOnly: false);
        var roadLanePointLookup = system.GetBufferLookup<RoadLanePoint>(isReadOnly: false);
        var roadLaneNeighbourLookup = system.GetBufferLookup<RoadLaneNeighbour>(isReadOnly: false);
        var roadLaneUpdatePointsLookupAspectEnabledRef = system.GetComponentLookup<RoadLaneUpdatePoints>(isReadOnly: false);
        var roadLaneUpdateNeighboursLookupAspectEnabledRef = system.GetComponentLookup<RoadLaneUpdateNeighbours>(isReadOnly: false);
        Data = new AspectRef<RoadLaneData>(roadLaneDataLookup, entity, isReadOnly: false);
        Points = roadLanePointLookup[entity];
        Neighbours = roadLaneNeighbourLookup[entity];
        UpdatePoints = new AspectEnabledRef<RoadLaneUpdatePoints>(roadLaneUpdatePointsLookupAspectEnabledRef, entity, isReadOnly: false);
        UpdateNeighbours = new AspectEnabledRef<RoadLaneUpdateNeighbours>(roadLaneUpdateNeighboursLookupAspectEnabledRef, entity, isReadOnly: false);
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new RoadLaneAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public RoadLaneAspect Set(LookupSlot<RoadLaneData> slot)
    {
        Data = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadLaneAspect Set(LookupSlot<RoadLaneData> slot, bool isReadOnly)
    {
        Data = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadLaneAspect Set(BufferSlot<RoadLanePoint> slot)
    {
        Points = slot.Bind(Entity);
        return this;
    }

    public RoadLaneAspect Set(BufferSlot<RoadLaneNeighbour> slot)
    {
        Neighbours = slot.Bind(Entity);
        return this;
    }

    public RoadLaneAspect Set(EnableableSlot<RoadLaneUpdatePoints> slot)
    {
        UpdatePoints = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadLaneAspect Set(EnableableSlot<RoadLaneUpdatePoints> slot, bool isReadOnly)
    {
        UpdatePoints = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadLaneAspect Set(EnableableSlot<RoadLaneUpdateNeighbours> slot)
    {
        UpdateNeighbours = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadLaneAspect Set(EnableableSlot<RoadLaneUpdateNeighbours> slot, bool isReadOnly)
    {
        UpdateNeighbours = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadLaneAspect Set(ComponentLookup<RoadLaneData> lookup, bool isReadOnly = true)
    {
        Data = new AspectRef<RoadLaneData>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadLaneAspect Set(BufferLookup<RoadLanePoint> lookup)
    {
        Points = lookup[Entity];
        return this;
    }

    public RoadLaneAspect Set(BufferLookup<RoadLaneNeighbour> lookup)
    {
        Neighbours = lookup[Entity];
        return this;
    }

    public RoadLaneAspect Set(ComponentLookup<RoadLaneUpdatePoints> lookup, bool isReadOnly = true)
    {
        UpdatePoints = new AspectEnabledRef<RoadLaneUpdatePoints>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadLaneAspect Set(ComponentLookup<RoadLaneUpdateNeighbours> lookup, bool isReadOnly = true)
    {
        UpdateNeighbours = new AspectEnabledRef<RoadLaneUpdateNeighbours>(lookup, Entity, isReadOnly);
        return this;
    }

    // From IJobEntity Execute parameters.
    public RoadLaneAspect Set(RefRO<RoadLaneData> value)
    {
        Data = new AspectRef<RoadLaneData>(value);
        return this;
    }
    public RoadLaneAspect Set(RefRW<RoadLaneData> value)
    {
        Data = new AspectRef<RoadLaneData>(value);
        return this;
    }
    public RoadLaneAspect Set(DynamicBuffer<RoadLanePoint> buffer)
    {
        Points = buffer;
        return this;
    }
    public RoadLaneAspect Set(DynamicBuffer<RoadLaneNeighbour> buffer)
    {
        Neighbours = buffer;
        return this;
    }
    public RoadLaneAspect Set(EnabledRefRO<RoadLaneUpdatePoints> value)
    {
        UpdatePoints = new AspectEnabledRef<RoadLaneUpdatePoints>(value);
        return this;
    }
    public RoadLaneAspect Set(EnabledRefRW<RoadLaneUpdatePoints> value)
    {
        UpdatePoints = new AspectEnabledRef<RoadLaneUpdatePoints>(value);
        return this;
    }
    public RoadLaneAspect Set(EnabledRefRO<RoadLaneUpdateNeighbours> value)
    {
        UpdateNeighbours = new AspectEnabledRef<RoadLaneUpdateNeighbours>(value);
        return this;
    }
    public RoadLaneAspect Set(EnabledRefRW<RoadLaneUpdateNeighbours> value)
    {
        UpdateNeighbours = new AspectEnabledRef<RoadLaneUpdateNeighbours>(value);
        return this;
    }
    #endregion </auto-generated-lookup>
   
    public Entity Entity;
    public AspectRef<RoadLaneData> Data;
    public DynamicBuffer<RoadLanePoint> Points;
    public DynamicBuffer<RoadLaneNeighbour> Neighbours;
    public AspectEnabledRef<RoadLaneUpdatePoints> UpdatePoints;
    public AspectEnabledRef<RoadLaneUpdateNeighbours> UpdateNeighbours;

    public void SetParent(RoadSegmentEnt roadSegmentEnt) => Data.ValueRW.Parent = roadSegmentEnt;
    public void SetStartPort(RoadPortEnt roadPortEnt) => Data.ValueRW.StartPortEnt = roadPortEnt;
    public void SetEndPort(RoadPortEnt roadPortEnt) => Data.ValueRW.EndPortEnt = roadPortEnt;
    public void SetLaneWidth(float laneWidth) => Data.ValueRW.LaneWidth = laneWidth;

    public float3 GetPointAtDist(float dist)
    {
        if (Points.Length == 0)
            return float3.zero;
        float totalDist = 0f;
        for (int i = 0; i < Points.Length - 1; i++)
        {
            float segmentDist = math.distance(Points[i].Position, Points[i + 1].Position);
            if (totalDist + segmentDist >= dist)
            {
                float t = (dist - totalDist) / segmentDist;
                return math.lerp(Points[i].Position, Points[i + 1].Position, t);
            }
            totalDist += segmentDist;
        }
        return Points[^1].Position;
    }
    public float3 GetPointAtFract(float fract)
    {
        float roadLength = Points[^1].Distance;
        float dist = roadLength * fract;
        return GetPointAtDist(dist);
    }
}