// GenerateAspectLookups.cpp
// Usage: GenerateAspectLookups.exe <item_path> <project_root>
//
// For every *.cs file targeted:
//   - finds each `struct X : IAspect`
//   - collects fields of type RefRW<T> / RefRO<T> / EnabledRefRW<T> /
//     EnabledRefRO<T> / AspectRef<T> / AspectEnabledRef<T> / DynamicBuffer<T>
//     (with optional [OptionalLookup])
//   - deletes the previously generated region and regenerates, at the top of
//     the aspect body:
//        * an entity-only constructor, for chained Set() assembly
//        * constructors taking (ref SystemState, Entity) and (SystemBase,
//          Entity), which bind every field through temporary lookups
//        * Set(...) overloads per field, each returning the aspect so calls
//          chain:  new MyAspect(e).Set(dataSlot).Set(pointsBuffer)
//          - slot forms  (LookupSlot / EnableableSlot / BufferSlot)
//          - raw lookup forms (ComponentLookup / BufferLookup)
//          - Execute-parameter forms (RefRO/RefRW/EnabledRef*/DynamicBuffer)
//
// There is no generated Lookup struct: systems declare only the slots they
// use, which keeps unrelated containers out of job data.
//
// Requires /std:c++17 or later.

#include <cctype>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static const std::string kBeginMark = "#region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups";
static const std::string kEndMark = "#endregion </auto-generated-lookup>";

struct AspectField
{
    std::string componentType;  // e.g. "LocalTransform" (namespace stripped)
    std::string fieldName;      // e.g. "LocalTransformRW"
    std::string kind;           // wrapper type name, e.g. "RefRW", "AspectRef"
    bool        rw = false;     // RefRW vs RefRO (ignored for buffers)
    bool        buffer = false; // DynamicBuffer<T>
    bool        enableable = false; // EnabledRef* / AspectEnabledRef
    bool        tolerant = false;   // AspectRef<T> / AspectEnabledRef<T>
    bool        optional = false;

    // Data and buffer slots keep the plain {Component}Lookup name (so RefRO
    // and RefRW of the same component share one slot). Enable-bit slots get
    // the wrapper kind appended, so they can sit alongside the data slot of
    // the same component type.
    std::string SlotName() const
    {
        return componentType + "Lookup" + (enableable ? kind : "");
    }

    std::string SlotDecl() const
    {
        const char* tmpl = buffer ? "BufferSlot<"
            : enableable ? "EnableableSlot<"
            : "LookupSlot<";
        return std::string(tmpl) + componentType + ">";
    }

    std::string BindCall() const
    {
        if (buffer)
            return SlotName() + (optional ? ".BindOptional(e)" : ".Bind(e)");

        std::string bind = tolerant ? "BindRef" : (rw ? "BindRW" : "BindRO");
        if (optional) bind += "Optional";
        return SlotName() + "." + bind + "(e)";
    }

    // Local variable name for this slot's temporary lookup. Derived from
    // SlotName (not the component type) so a component with both a data slot
    // and an enable-bit slot gets two distinct locals.
    std::string LocalName() const
    {
        std::string n = SlotName();
        if (!n.empty()) n[0] = (char)std::tolower((unsigned char)n[0]);
        return n;
    }

    // Assignment expression built from that local, e.g.
    //   localLookup.GetRefRW(entity)
    //   localLookup.HasComponent(entity) ? localLookup.GetRefRO(entity) : default
    std::string LookupCall(const std::string& e) const
    {
        const std::string L = LocalName();
        std::string call;
        if (buffer)
            call = L + "[" + e + "]";
        else if (tolerant && enableable)
            call = "new AspectEnabledRef<" + componentType + ">(" + L + ", " + e + ", isReadOnly: false)";
        else if (tolerant)
            call = "new AspectRef<" + componentType + ">(" + L + ", " + e + ", isReadOnly: false)";
        else if (enableable)
            call = L + (rw ? ".GetEnabledRefRW<" : ".GetEnabledRefRO<") + componentType + ">(" + e + ")";
        else
            call = L + (rw ? ".GetRefRW(" : ".GetRefRO(") + e + ")";

        if (optional)
        {
            std::string has = L + (buffer ? ".HasBuffer(" : ".HasComponent(") + e + ")";
            call = has + " ? " + call + " : default";
        }
        return call;
    }
};

static std::string ReadFile(const fs::path& p)
{
    std::ifstream in(p, std::ios::binary);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

static void WriteFile(const fs::path& p, const std::string& text)
{
    std::ofstream out(p, std::ios::binary);
    out << text;
}

// Given index of '{' in s, return index of its matching '}' (or npos).
// Skips braces inside strings, chars, and // or /* */ comments.
static size_t FindMatchingBrace(const std::string& s, size_t open)
{
    int depth = 0;
    for (size_t i = open; i < s.size(); ++i)
    {
        char c = s[i];
        if (c == '/' && i + 1 < s.size() && s[i + 1] == '/')
        {
            i = s.find('\n', i);
            if (i == std::string::npos) return std::string::npos;
        }
        else if (c == '/' && i + 1 < s.size() && s[i + 1] == '*')
        {
            i = s.find("*/", i + 2);
            if (i == std::string::npos) return std::string::npos;
            ++i; // lands on '/'
        }
        else if (c == '"' || c == '\'')
        {
            char quote = c;
            for (++i; i < s.size(); ++i)
            {
                if (s[i] == '\\') { ++i; continue; }
                if (s[i] == quote) break;
            }
        }
        else if (c == '{') ++depth;
        else if (c == '}')
        {
            if (--depth == 0) return i;
        }
    }
    return std::string::npos;
}

// Convert bare \n in generated text to \r\n when the source file uses CRLF.
static std::string MatchNewlines(const std::string& generated, bool crlf)
{
    if (!crlf) return generated;
    std::string out;
    out.reserve(generated.size() + generated.size() / 16);
    for (char c : generated)
    {
        if (c == '\n') out += "\r\n";
        else out += c;
    }
    return out;
}

static std::string StripNamespace(const std::string& type)
{
    size_t dot = type.rfind('.');
    return dot == std::string::npos ? type : type.substr(dot + 1);
}

// Indentation of the line containing position pos.
static std::string LineIndent(const std::string& s, size_t pos)
{
    size_t lineStart = s.rfind('\n', pos);
    lineStart = (lineStart == std::string::npos) ? 0 : lineStart + 1;
    std::string indent;
    for (size_t i = lineStart; i < s.size() && (s[i] == ' ' || s[i] == '\t'); ++i)
        indent += s[i];
    return indent;
}

// Erase [start, end) expanded to whole lines.
static void EraseLines(std::string& body, size_t start, size_t end)
{
    size_t lineStart = body.rfind('\n', start);
    lineStart = (lineStart == std::string::npos) ? 0 : lineStart + 1;
    while (end < body.size() && (body[end] == '\r' || body[end] == '\n'))
        ++end;
    body.erase(lineStart, end - lineStart);
}

// Legacy path: remove a bare `struct Lookup { ... }` written before sentinels
// existed. Returns true if removed.
static bool RemoveExistingLookup(std::string& body)
{
    static const std::regex lookupDecl(
        R"((?:public\s+|internal\s+|readonly\s+|partial\s+)*struct\s+Lookup\b)");

    std::smatch m;
    if (!std::regex_search(body, m, lookupDecl))
        return false;

    size_t declStart = (size_t)m.position(0);
    size_t open = body.find('{', declStart + m.length(0));
    if (open == std::string::npos) return false;
    size_t close = FindMatchingBrace(body, open);
    if (close == std::string::npos) return false;

    EraseLines(body, declStart, close + 1);
    return true;
}

// Remove the sentinel-delimited generated region; fall back to the legacy
// Lookup-only removal for files produced by earlier versions.
static bool RemoveGenerated(std::string& body)
{
    size_t b = body.find(kBeginMark);
    if (b != std::string::npos)
    {
        size_t e = body.find(kEndMark, b);
        if (e != std::string::npos)
        {
            EraseLines(body, b, e + kEndMark.size());
            return true;
        }
    }
    return RemoveExistingLookup(body);
}

static std::vector<AspectField> CollectFields(const std::string& body)
{
    // groups: 1 = [OptionalLookup], 2 = wrapper type name,
    //         3 = component type, 4 = field name
    // Longer names first so e.g. EnabledRefRW wins over RefRW.
    static const std::regex fieldRe(
        R"((\[\s*OptionalLookup\s*\]\s*)?(?:public\s+|internal\s+|private\s+|readonly\s+)*(AspectEnabledRef|AspectRef|EnabledRefRW|EnabledRefRO|RefRW|RefRO|DynamicBuffer)\s*<\s*([\w\.]+)\s*>\s+(\w+)\s*;)");

    std::vector<AspectField> fields;
    for (auto it = std::sregex_iterator(body.begin(), body.end(), fieldRe);
        it != std::sregex_iterator(); ++it)
    {
        // Guard against matching mid-identifier (e.g. MyRefRW<T>): std::regex
        // has no lookbehind, so check the preceding character by hand.
        size_t pos = (size_t)it->position(0);
        if (pos > 0)
        {
            char prev = body[pos - 1];
            if (std::isalnum((unsigned char)prev) || prev == '_')
                continue;
        }

        const std::string kind = (*it)[2].str();

        AspectField f;
        f.kind = kind;
        f.optional = (*it)[1].matched;
        f.buffer = (kind == "DynamicBuffer");
        f.tolerant = (kind == "AspectRef" || kind == "AspectEnabledRef");
        f.enableable = (kind == "EnabledRefRW" || kind == "EnabledRefRO"
            || kind == "AspectEnabledRef");
        f.rw = (kind == "RefRW" || kind == "EnabledRefRW");
        f.componentType = StripNamespace((*it)[3].str());
        f.fieldName = (*it)[4].str();
        fields.push_back(f);
    }
    return fields;
}

static std::string DetectEntityFieldName(const std::string& body)
{
    static const std::regex entityRe(R"(public\s+Entity\s+(\w+)\s*;)");
    std::smatch m;
    if (std::regex_search(body, m, entityRe))
        return m[1].str();
    return "Entity";
}

static std::string GenerateLookup(const std::string& aspectName,
    const std::string& entityField,
    const std::vector<AspectField>& fields,
    const std::string& ind) // indent of aspect members
{
    const std::string i1 = ind;
    const std::string i2 = ind + "    ";
    const std::string i3 = ind + "        ";

    // One slot per component type, for the full constructors' locals.
    std::vector<const AspectField*> slots;
    for (const auto& f : fields)
    {
        bool seen = false;
        for (const auto* s : slots) if (s->SlotName() == f.SlotName()) { seen = true; break; }
        if (!seen) slots.push_back(&f);
    }

    std::ostringstream o;
    o << i1 << kBeginMark << "\n";

    // ---- entity-only constructor -----------------------------------------
    o << i1 << "/// Entity-only: bind fields afterwards with chained Set(...).\n";
    o << i1 << "public " << aspectName << "(Entity entity)\n";
    o << i1 << "{\n";
    o << i2 << "this = default;\n";
    o << i2 << entityField << " = entity;\n";
    o << i1 << "}\n";

    // ---- full constructors ------------------------------------------------
    auto slotIsReadOnly = [&](const AspectField* slot)
        {
            for (const auto& f : fields)
                if (f.SlotName() == slot->SlotName() && (f.rw || f.tolerant || f.buffer))
                    return false;
            return true;
        };

    auto emitCtor = [&](const std::string& paramList,
        const std::string& compLookup,
        const std::string& bufLookup)
        {
            o << i1 << "public " << aspectName << "(" << paramList << ")\n";
            o << i1 << "{\n";
            o << i2 << "this = default;\n";
            o << i2 << entityField << " = entity;\n";
            for (const auto* s : slots)
            {
                const std::string ro = slotIsReadOnly(s) ? "true" : "false";
                o << i2 << "var " << s->LocalName() << " = "
                    << (s->buffer ? bufLookup : compLookup)
                    << "<" << s->componentType << ">(isReadOnly: " << ro << ");\n";
            }
            for (const auto& f : fields)
                o << i2 << f.fieldName << " = " << f.LookupCall("entity") << ";\n";
            o << i1 << "}\n";
        };

    o << "\n";
    o << i1 << "/// Binds every field through temporary lookups. Main-thread use;\n";
    o << i1 << "/// prefer declared slots + chained Set(...) inside systems.\n";
    emitCtor("ref SystemState state, Entity entity",
        "state.GetComponentLookup", "state.GetBufferLookup");
    o << "\n";
    o << i1 << "/// SystemBase / managed system variant.\n";
    emitCtor("SystemBase system, Entity entity",
        "system.GetComponentLookup", "system.GetBufferLookup");

    // ---- Set overloads ----------------------------------------------------
    auto slotParamType = [](const AspectField& f)
        {
            const char* tmpl = f.buffer ? "BufferSlot<"
                : f.enableable ? "EnableableSlot<"
                : "LookupSlot<";
            return std::string(tmpl) + f.componentType + ">";
        };
    auto rawParamType = [](const AspectField& f)
        {
            return (f.buffer ? "BufferLookup<" : "ComponentLookup<") + f.componentType + ">";
        };
    // Only the raw-lookup family can collide (data + enable bit of the same
    // component both take ComponentLookup<T>).
    auto rawMethodName = [&](const AspectField& f)
        {
            size_t same = 0;
            for (const auto& g : fields)
                if (rawParamType(g) == rawParamType(f)) ++same;
            return same > 1 ? "Set" + f.fieldName : std::string("Set");
        };

    auto optSuffix = [](const AspectField& f) { return f.optional ? "Optional" : ""; };

    o << "\n";
    o << i1 << "// Set(...) overloads. Each returns the aspect, so calls chain:\n";
    o << i1 << "//   new " << aspectName << "(e).Set(slotA).Set(bufferB);\n";
    o << i1 << "// Statement form works too — Set mutates this and returns a copy.\n";

    // --- slot forms ---
    for (const auto& f : fields)
    {
        std::string bind = f.buffer ? "Bind"
            : f.tolerant ? "BindRef"
            : (f.rw ? "BindRW" : "BindRO");
        bind += optSuffix(f);

        o << "\n" << i1 << "public " << aspectName << " Set(" << slotParamType(f) << " slot)\n";
        o << i1 << "{\n";
        o << i2 << f.fieldName << " = slot." << bind << "(" << entityField << ");\n";
        o << i2 << "return this;\n";
        o << i1 << "}\n";

        // Explicit-mode overload only where the mode is a real choice.
        if (f.tolerant)
        {
            o << i1 << "/// Explicit mode: isReadOnly: true downgrades a read-write\n";
            o << i1 << "/// slot; isReadOnly: false on a read-only slot throws.\n";
            o << i1 << "public " << aspectName << " Set(" << slotParamType(f)
                << " slot, bool isReadOnly)\n";
            o << i1 << "{\n";
            o << i2 << f.fieldName << " = slot." << bind << "(" << entityField << ", isReadOnly);\n";
            o << i2 << "return this;\n";
            o << i1 << "}\n";
        }
    }

    // --- raw lookup forms ---
    for (const auto& f : fields)
    {
        std::string expr;
        if (f.buffer)
            expr = "lookup[" + entityField + "]";
        else if (f.tolerant && f.enableable)
            expr = "new AspectEnabledRef<" + f.componentType + ">(lookup, " + entityField + ", isReadOnly)";
        else if (f.tolerant)
            expr = "new AspectRef<" + f.componentType + ">(lookup, " + entityField + ", isReadOnly)";
        else if (f.enableable)
            expr = std::string("lookup") + (f.rw ? ".GetEnabledRefRW<" : ".GetEnabledRefRO<")
            + f.componentType + ">(" + entityField + ")";
        else
            expr = std::string("lookup") + (f.rw ? ".GetRefRW(" : ".GetRefRO(") + entityField + ")";

        o << "\n" << i1 << "public " << aspectName << " " << rawMethodName(f)
            << "(" << rawParamType(f) << " lookup";
        // Defaults to read-only: a raw ComponentLookup does not expose the
        // mode it was created with, and binding read-only is the safe guess —
        // pass isReadOnly: false explicitly to take a write handle.
        if (f.tolerant) o << ", bool isReadOnly = true";
        o << ")\n";
        o << i1 << "{\n";
        o << i2 << f.fieldName << " = " << expr << ";\n";
        o << i2 << "return this;\n";
        o << i1 << "}\n";
    }

    // --- Execute-parameter forms ---
    // A RefRW argument can feed a RefRO field (explicit conversion); a RefRO
    // argument cannot feed a RefRW field, so that overload is not emitted —
    // the mismatch is a compile error rather than a runtime throw.
    o << "\n" << i1 << "// From IJobEntity Execute parameters.\n";
    for (const auto& f : fields)
    {
        if (f.buffer)
        {
            o << i1 << "public " << aspectName << " Set(DynamicBuffer<" << f.componentType << "> buffer)\n";
            o << i1 << "{\n" << i2 << f.fieldName << " = buffer;\n" << i2 << "return this;\n" << i1 << "}\n";
            continue;
        }

        const std::string roT = (f.enableable ? "EnabledRefRO<" : "RefRO<") + f.componentType + ">";
        const std::string rwT = (f.enableable ? "EnabledRefRW<" : "RefRW<") + f.componentType + ">";

        if (f.tolerant)
        {
            const std::string wrap = f.enableable
                ? "new AspectEnabledRef<" + f.componentType + ">("
                : "new AspectRef<" + f.componentType + ">(";
            o << i1 << "public " << aspectName << " Set(" << roT << " value)\n";
            o << i1 << "{\n" << i2 << f.fieldName << " = " << wrap << "value);\n"
                << i2 << "return this;\n" << i1 << "}\n";
            o << i1 << "public " << aspectName << " Set(" << rwT << " value)\n";
            o << i1 << "{\n" << i2 << f.fieldName << " = " << wrap << "value);\n"
                << i2 << "return this;\n" << i1 << "}\n";
        }
        else if (f.rw)
        {
            o << i1 << "public " << aspectName << " Set(" << rwT << " value)\n";
            o << i1 << "{\n" << i2 << f.fieldName << " = value;\n"
                << i2 << "return this;\n" << i1 << "}\n";
        }
        else
        {
            o << i1 << "public " << aspectName << " Set(" << roT << " value)\n";
            o << i1 << "{\n" << i2 << f.fieldName << " = value;\n"
                << i2 << "return this;\n" << i1 << "}\n";
            if (!f.enableable)   // RefRW -> RefRO conversion exists; enable-bit has none
            {
                o << i1 << "public " << aspectName << " Set(" << rwT << " value)\n";
                o << i1 << "{\n" << i2 << f.fieldName << " = (" << roT << ")value;\n"
                    << i2 << "return this;\n" << i1 << "}\n";
            }
        }
    }

    o << i1 << kEndMark << "\n";
    return o.str();
}

// Process one file. Returns true if the file was modified.
static bool ProcessFile(const fs::path& path)
{
    std::string text = ReadFile(path);

    // Find every `struct X : <bases containing IAspect>`.
    static const std::regex aspectRe(R"(struct\s+(\w+)\s*:\s*([^\{]*))");

    struct AspectSpan { std::string name; size_t open, close; };
    std::vector<AspectSpan> aspects;

    for (auto it = std::sregex_iterator(text.begin(), text.end(), aspectRe);
        it != std::sregex_iterator(); ++it)
    {
        if (!std::regex_search((*it)[2].str(), std::regex(R"(\bIAspect\b)")))
            continue;
        size_t open = text.find('{', (size_t)it->position(0) + it->length(0) - 1);
        if (open == std::string::npos) continue;
        size_t close = FindMatchingBrace(text, open);
        if (close == std::string::npos) continue;
        aspects.push_back({ (*it)[1].str(), open, close });
    }

    if (aspects.empty())
        return false;

    bool modified = false;

    // Process back-to-front so earlier spans stay valid.
    for (auto a = aspects.rbegin(); a != aspects.rend(); ++a)
    {
        std::string body = text.substr(a->open + 1, a->close - a->open - 1);

        RemoveGenerated(body);
        std::vector<AspectField> fields = CollectFields(body);
        if (fields.empty())
        {
            std::printf("  %s: no Ref/EnabledRef/DynamicBuffer fields, skipped\n", a->name.c_str());
            continue;
        }

        size_t enableables = 0;
        for (const auto& f : fields) if (f.enableable) ++enableables;

        std::string entityField = DetectEntityFieldName(body);
        std::string memberIndent = LineIndent(text, a->open) + "    ";
        bool crlf = text.find("\r\n") != std::string::npos;
        std::string lookup = MatchNewlines(
            GenerateLookup(a->name, entityField, fields, memberIndent), crlf);

        // Append generated region at the end of the (cleaned) body, keeping
        // the hand-written fields and methods at the top of the struct.
        size_t tail = body.size();
        while (tail > 0 && (body[tail - 1] == ' ' || body[tail - 1] == '\t'))
            --tail;                       // drop the closing brace's indent
        std::string trailing = body.substr(tail);   // put it back afterwards

        std::string head = body.substr(0, tail);
        // Ensure exactly one blank line before the region.
        while (!head.empty() && (head.back() == '\r' || head.back() == '\n'))
            head.pop_back();
        const std::string nl = crlf ? "\r\n" : "\n";
        body = head + nl + nl + lookup + trailing;

        text = text.substr(0, a->open + 1) + body + text.substr(a->close);
        modified = true;
        std::printf("  %s: generated Lookup + ctor, %zu field(s), %zu enableable\n",
            a->name.c_str(), fields.size(), enableables);
    }

    if (modified)
        WriteFile(path, text);
    return modified;
}

int main(int argc, char* argv[])
{
    if (argc < 2)
    {
        std::printf("usage: GenerateAspectLookups.exe <item_path> [project_root]\n");
        return 1;
    }

    fs::path item(argv[1]);
    int changed = 0;

    auto handle = [&](const fs::path& p)
        {
            std::printf("%s\n", p.string().c_str());
            if (ProcessFile(p)) ++changed;
        };

    if (fs::is_directory(item))
    {
        for (auto& e : fs::recursive_directory_iterator(item))
            if (e.is_regular_file() && e.path().extension() == ".cs")
                handle(e.path());
    }
    else if (fs::exists(item))
    {
        handle(item);
    }
    else
    {
        std::printf("path not found: %s\n", item.string().c_str());
        return 1;
    }

    std::printf("Done. %d file(s) modified.\n", changed);
    return 0;
}