using System.Collections.Generic;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

public struct RoadNodeData : IComponentData
{
    public Line2D line2D;
}

[InternalBufferCapacity(2)]
public struct RoadNodePortChild : IBufferElementData
{
    public RoadPortEnt PortEnt;
}

public struct RoadNodeAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public RoadNodeAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public RoadNodeAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadNodeDataLookup = state.GetComponentLookup<RoadNodeData>(isReadOnly: false);
        var roadNodePortChildLookup = state.GetBufferLookup<RoadNodePortChild>(isReadOnly: false);
        Data = roadNodeDataLookup.GetRefRW(entity);
        ChildPorts = roadNodePortChildLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadNodeAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadNodeDataLookup = system.GetComponentLookup<RoadNodeData>(isReadOnly: false);
        var roadNodePortChildLookup = system.GetBufferLookup<RoadNodePortChild>(isReadOnly: false);
        Data = roadNodeDataLookup.GetRefRW(entity);
        ChildPorts = roadNodePortChildLookup[entity];
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new RoadNodeAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public RoadNodeAspect Set(LookupSlot<RoadNodeData> slot)
    {
        Data = slot.BindRW(Entity);
        return this;
    }

    public RoadNodeAspect Set(BufferSlot<RoadNodePortChild> slot)
    {
        ChildPorts = slot.Bind(Entity);
        return this;
    }

    public RoadNodeAspect Set(ComponentLookup<RoadNodeData> lookup)
    {
        Data = lookup.GetRefRW(Entity);
        return this;
    }

    public RoadNodeAspect Set(BufferLookup<RoadNodePortChild> lookup)
    {
        ChildPorts = lookup[Entity];
        return this;
    }

    // From IJobEntity Execute parameters.
    public RoadNodeAspect Set(RefRW<RoadNodeData> value)
    {
        Data = value;
        return this;
    }
    public RoadNodeAspect Set(DynamicBuffer<RoadNodePortChild> buffer)
    {
        ChildPorts = buffer;
        return this;
    }
    #endregion </auto-generated-lookup>
    public Entity Entity;
    public RefRW<RoadNodeData> Data;
    public DynamicBuffer<RoadNodePortChild> ChildPorts;

    public bool AddChild(RoadPortEnt port)
    {
        // find duplicates
        for (int i = 0; i < ChildPorts.Length; i++)
            if (ChildPorts[i].PortEnt == port)
                return false;
        ChildPorts.Add(new RoadNodePortChild { PortEnt = port });
        return true;
    }
    public void RecalculateLane(NativeArray<float2> portPositions)
    {
        Data.ValueRW.line2D = new Line2D(portPositions);
    }
    public void SortChildren(RoadPortAspect.Lookup PortAspectLookup)
    {
        ChildPorts.AsNativeArray().Sort(Comparer<RoadNodePortChild>.Create((a, b) =>
        {
            var aPos = PortAspectLookup[a.PortEnt].Position;
            var bPos = PortAspectLookup[b.PortEnt].Position;
            if(math.abs(aPos.x - bPos.x) > 0.001f)
                return aPos.x.CompareTo(bPos.x);
            if(math.abs(aPos.y - bPos.y) > 0.001f)
                return aPos.y.CompareTo(bPos.y);
            return aPos.z.CompareTo(bPos.z);
        }));
    }
}
