using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

public struct rgRoadNodeData : IComponentData
{
    public Line2D line2D;
}

[InternalBufferCapacity(2)]
public struct rgRoadPortChild : IBufferElementData
{
    public RoadPortEnt PortEnt;
}

public struct RoadNodeAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    public struct Lookup
    {
        public LookupSlot<rgRoadNodeData> rgRoadNodeDataLookup;
        public BufferSlot<rgRoadPortChild> rgRoadPortChildLookup;
        public void Initialize(ref SystemState state)
        {
            rgRoadNodeDataLookup.Initialize(ref state);
            rgRoadPortChildLookup.Initialize(ref state);
        }
        /// SystemBase / managed system variant.
        public void Initialize(ComponentSystemBase system)
        {
            rgRoadNodeDataLookup.Initialize(system);
            rgRoadPortChildLookup.Initialize(system);
        }
        public void Update(ref SystemState state)
        {
            rgRoadNodeDataLookup.Update(ref state);
            rgRoadPortChildLookup.Update(ref state);
        }
        public void Update(SystemBase system)
        {
            rgRoadNodeDataLookup.Update(system);
            rgRoadPortChildLookup.Update(system);
        }
        public RoadNodeAspect this[Entity e] => new RoadNodeAspect
        {
            Entity = e,
            Data = rgRoadNodeDataLookup.BindRW(e),
            ChildPorts = rgRoadPortChildLookup.Bind(e)
        };
    }

    /// Main-thread construction without a cached Lookup: builds
    /// temporary lookups for this entity. Not usable inside jobs.
    /// (EntityManager cannot return RefRO/RefRW for an entity.)
    public RoadNodeAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var rgRoadNodeDataLookup = state.GetComponentLookup<rgRoadNodeData>(isReadOnly: false);
        var rgRoadPortChildLookup = state.GetBufferLookup<rgRoadPortChild>(isReadOnly: false);
        Data = rgRoadNodeDataLookup.GetRefRW(entity);
        ChildPorts = rgRoadPortChildLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadNodeAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var rgRoadNodeDataLookup = system.GetComponentLookup<rgRoadNodeData>(isReadOnly: false);
        var rgRoadPortChildLookup = system.GetBufferLookup<rgRoadPortChild>(isReadOnly: false);
        Data = rgRoadNodeDataLookup.GetRefRW(entity);
        ChildPorts = rgRoadPortChildLookup[entity];
    }
    #endregion </auto-generated-lookup>

    public Entity Entity;
    public RefRW<rgRoadNodeData> Data;
    public DynamicBuffer<rgRoadPortChild> ChildPorts;

    public bool AddChild(RoadPortEnt port)
    {
        // find duplicates
        for (int i = 0; i < ChildPorts.Length; i++)
            if (ChildPorts[i].PortEnt == port)
                return false;
        ChildPorts.Add(new rgRoadPortChild { PortEnt = port });
        return true;
    }
    public void RecalculateLane(NativeArray<float2> portPositions)
    {
        Data.ValueRW.line2D = new Line2D(portPositions);
    }
}
