using Unity.Entities;

public struct RoadSegmentData : IComponentData
{
}

[InternalBufferCapacity(2)]
public struct RoadSegmentNode : IBufferElementData
{
    public RoadNodeEnt NodeEnt;
}

[InternalBufferCapacity(2)]
public struct RoadSegmentLane : IBufferElementData
{
    public RoadLaneEnt LaneEnt;
}

public struct RoadSegmentAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public RoadSegmentAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public RoadSegmentAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadSegmentDataLookup = state.GetComponentLookup<RoadSegmentData>(isReadOnly: false);
        var roadSegmentNodeLookup = state.GetBufferLookup<RoadSegmentNode>(isReadOnly: false);
        var roadSegmentLaneLookup = state.GetBufferLookup<RoadSegmentLane>(isReadOnly: false);
        Data = roadSegmentDataLookup.GetRefRW(entity);
        Nodes = roadSegmentNodeLookup[entity];
        ChildLanes = roadSegmentLaneLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadSegmentAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadSegmentDataLookup = system.GetComponentLookup<RoadSegmentData>(isReadOnly: false);
        var roadSegmentNodeLookup = system.GetBufferLookup<RoadSegmentNode>(isReadOnly: false);
        var roadSegmentLaneLookup = system.GetBufferLookup<RoadSegmentLane>(isReadOnly: false);
        Data = roadSegmentDataLookup.GetRefRW(entity);
        Nodes = roadSegmentNodeLookup[entity];
        ChildLanes = roadSegmentLaneLookup[entity];
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new RoadSegmentAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public RoadSegmentAspect Set(LookupSlot<RoadSegmentData> slot)
    {
        Data = slot.BindRW(Entity);
        return this;
    }

    public RoadSegmentAspect Set(BufferSlot<RoadSegmentNode> slot)
    {
        Nodes = slot.Bind(Entity);
        return this;
    }

    public RoadSegmentAspect Set(BufferSlot<RoadSegmentLane> slot)
    {
        ChildLanes = slot.Bind(Entity);
        return this;
    }

    public RoadSegmentAspect Set(ComponentLookup<RoadSegmentData> lookup)
    {
        Data = lookup.GetRefRW(Entity);
        return this;
    }

    public RoadSegmentAspect Set(BufferLookup<RoadSegmentNode> lookup)
    {
        Nodes = lookup[Entity];
        return this;
    }

    public RoadSegmentAspect Set(BufferLookup<RoadSegmentLane> lookup)
    {
        ChildLanes = lookup[Entity];
        return this;
    }

    // From IJobEntity Execute parameters.
    public RoadSegmentAspect Set(RefRW<RoadSegmentData> value)
    {
        Data = value;
        return this;
    }
    public RoadSegmentAspect Set(DynamicBuffer<RoadSegmentNode> buffer)
    {
        Nodes = buffer;
        return this;
    }
    public RoadSegmentAspect Set(DynamicBuffer<RoadSegmentLane> buffer)
    {
        ChildLanes = buffer;
        return this;
    }
    #endregion </auto-generated-lookup>
    public Entity Entity;
    public RefRW<RoadSegmentData> Data;
    public DynamicBuffer<RoadSegmentNode> Nodes;
    public DynamicBuffer<RoadSegmentLane> ChildLanes;

    public bool AddNode(RoadNodeEnt node)
    {
        // find duplicates
        for (int i = 0; i < Nodes.Length; i++)
            if (Nodes[i].NodeEnt == node)
                return false;
        Nodes.Add(new RoadSegmentNode { NodeEnt = node });
        return true;
    }

    public bool AddChildLane(RoadLaneEnt lane)
    {
        // find duplicates
        for (int i = 0; i < ChildLanes.Length; i++)
            if (ChildLanes[i].LaneEnt == lane)
                return false;
        ChildLanes.Add(new RoadSegmentLane { LaneEnt = lane });
        return true;
    }
}
