using Unity.Entities;

public struct rgRoadSegmentData : IComponentData
{
}

[InternalBufferCapacity(2)]
public struct rgRoadSegmentNode : IBufferElementData
{
    public RoadNodeEnt NodeEnt;
}

[InternalBufferCapacity(2)]
public struct rgRoadSegmentLane : IBufferElementData
{
    public RoadLaneEnt LaneEnt;
}

public struct RoadSegmentAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    public struct Lookup
    {
        public LookupSlot<rgRoadSegmentData> rgRoadSegmentDataLookup;
        public BufferSlot<rgRoadSegmentNode> rgRoadSegmentNodeLookup;
        public BufferSlot<rgRoadSegmentLane> rgRoadSegmentLaneLookup;
        public void Initialize(ref SystemState state)
        {
            rgRoadSegmentDataLookup.Initialize(ref state);
            rgRoadSegmentNodeLookup.Initialize(ref state);
            rgRoadSegmentLaneLookup.Initialize(ref state);
        }
        /// SystemBase / managed system variant.
        public void Initialize(ComponentSystemBase system)
        {
            rgRoadSegmentDataLookup.Initialize(system);
            rgRoadSegmentNodeLookup.Initialize(system);
            rgRoadSegmentLaneLookup.Initialize(system);
        }
        public void Update(ref SystemState state)
        {
            rgRoadSegmentDataLookup.Update(ref state);
            rgRoadSegmentNodeLookup.Update(ref state);
            rgRoadSegmentLaneLookup.Update(ref state);
        }
        public void Update(SystemBase system)
        {
            rgRoadSegmentDataLookup.Update(system);
            rgRoadSegmentNodeLookup.Update(system);
            rgRoadSegmentLaneLookup.Update(system);
        }
        public RoadSegmentAspect this[Entity e] => new RoadSegmentAspect
        {
            Entity = e,
            Data = rgRoadSegmentDataLookup.BindRW(e),
            Nodes = rgRoadSegmentNodeLookup.Bind(e),
            ChildLanes = rgRoadSegmentLaneLookup.Bind(e)
        };
    }

    /// Main-thread construction without a cached Lookup: builds
    /// temporary lookups for this entity. Not usable inside jobs.
    /// (EntityManager cannot return RefRO/RefRW for an entity.)
    public RoadSegmentAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var rgRoadSegmentDataLookup = state.GetComponentLookup<rgRoadSegmentData>(isReadOnly: false);
        var rgRoadSegmentNodeLookup = state.GetBufferLookup<rgRoadSegmentNode>(isReadOnly: false);
        var rgRoadSegmentLaneLookup = state.GetBufferLookup<rgRoadSegmentLane>(isReadOnly: false);
        Data = rgRoadSegmentDataLookup.GetRefRW(entity);
        Nodes = rgRoadSegmentNodeLookup[entity];
        ChildLanes = rgRoadSegmentLaneLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadSegmentAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var rgRoadSegmentDataLookup = system.GetComponentLookup<rgRoadSegmentData>(isReadOnly: false);
        var rgRoadSegmentNodeLookup = system.GetBufferLookup<rgRoadSegmentNode>(isReadOnly: false);
        var rgRoadSegmentLaneLookup = system.GetBufferLookup<rgRoadSegmentLane>(isReadOnly: false);
        Data = rgRoadSegmentDataLookup.GetRefRW(entity);
        Nodes = rgRoadSegmentNodeLookup[entity];
        ChildLanes = rgRoadSegmentLaneLookup[entity];
    }
    #endregion </auto-generated-lookup>

    public Entity Entity;
    public RefRW<rgRoadSegmentData> Data;
    public DynamicBuffer<rgRoadSegmentNode> Nodes;
    public DynamicBuffer<rgRoadSegmentLane> ChildLanes;

    public bool AddNode(RoadNodeEnt node)
    {
        // find duplicates
        for (int i = 0; i < Nodes.Length; i++)
            if (Nodes[i].NodeEnt == node)
                return false;
        Nodes.Add(new rgRoadSegmentNode { NodeEnt = node });
        return true;
    }

    public bool AddChildLane(RoadLaneEnt lane)
    {
        // find duplicates
        for (int i = 0; i < ChildLanes.Length; i++)
            if (ChildLanes[i].LaneEnt == lane)
                return false;
        ChildLanes.Add(new rgRoadSegmentLane { LaneEnt = lane });
        return true;
    }
}
