using Unity.Entities;
using Unity.Mathematics;
using Unity.Rendering;
using Unity.Transforms;
using UnityEngine;
using static Unity.Burst.Intrinsics.X86.Avx;

public struct RoadVisualizerData : IComponentData
{
    public Entity Parent;
}

public struct RoadVisualizerAspect : IAspect
{
    public Entity Entity;
    public AspectRef<RoadVisualizerData> Data;
    public AspectRef<LocalTransform> LocalTransform;
    public AspectRef<RuntimeUpdateableMesh> RuntimeUpdateableMesh;
    public AspectRef<MaterialMeshInfo> MaterialMeshInfo;
    public AspectRef<RenderBounds> RenderBounds;

    public Entity Parent
    {
        get { return Data.ValueRO.Parent; }
        set { Data.ValueRW.Parent = value; }
    }

    // TODO: Make so it reuses mesh already in RuntimeUpdateableMesh and not create a new one
    public void SetMesh(Mesh mesh, EntitiesGraphicsSystem EntitiesGraphicsSystem)
    {
        mesh.RecalculateBounds();
        var meshID = EntitiesGraphicsSystem.RegisterMesh(mesh);
        if (RuntimeUpdateableMesh.ValueRW.Mesh != null)
        {
            EntitiesGraphicsSystem.UnregisterMesh(RuntimeUpdateableMesh.ValueRW.Id);
            UnityEngine.Object.Destroy(RuntimeUpdateableMesh.ValueRW.Mesh);
        }

        RuntimeUpdateableMesh.ValueRW.Mesh = mesh;    
        RuntimeUpdateableMesh.ValueRW.Id = meshID;
        MaterialMeshInfo.ValueRW.MeshID = meshID;
        AABB AABB = new AABB { Center = mesh.bounds.center, Extents = mesh.bounds.extents };
        RenderBounds.ValueRW.Value = AABB;
    }

    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public RoadVisualizerAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public RoadVisualizerAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadVisualizerDataLookup = state.GetComponentLookup<RoadVisualizerData>(isReadOnly: false);
        var localTransformLookup = state.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var runtimeUpdateableMeshLookup = state.GetComponentLookup<RuntimeUpdateableMesh>(isReadOnly: false);
        var materialMeshInfoLookup = state.GetComponentLookup<MaterialMeshInfo>(isReadOnly: false);
        var renderBoundsLookup = state.GetComponentLookup<RenderBounds>(isReadOnly: false);
        Data = new AspectRef<RoadVisualizerData>(roadVisualizerDataLookup, entity, isReadOnly: false);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        RuntimeUpdateableMesh = new AspectRef<RuntimeUpdateableMesh>(runtimeUpdateableMeshLookup, entity, isReadOnly: false);
        MaterialMeshInfo = new AspectRef<MaterialMeshInfo>(materialMeshInfoLookup, entity, isReadOnly: false);
        RenderBounds = new AspectRef<RenderBounds>(renderBoundsLookup, entity, isReadOnly: false);
    }

    /// SystemBase / managed system variant.
    public RoadVisualizerAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadVisualizerDataLookup = system.GetComponentLookup<RoadVisualizerData>(isReadOnly: false);
        var localTransformLookup = system.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var runtimeUpdateableMeshLookup = system.GetComponentLookup<RuntimeUpdateableMesh>(isReadOnly: false);
        var materialMeshInfoLookup = system.GetComponentLookup<MaterialMeshInfo>(isReadOnly: false);
        var renderBoundsLookup = system.GetComponentLookup<RenderBounds>(isReadOnly: false);
        Data = new AspectRef<RoadVisualizerData>(roadVisualizerDataLookup, entity, isReadOnly: false);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        RuntimeUpdateableMesh = new AspectRef<RuntimeUpdateableMesh>(runtimeUpdateableMeshLookup, entity, isReadOnly: false);
        MaterialMeshInfo = new AspectRef<MaterialMeshInfo>(materialMeshInfoLookup, entity, isReadOnly: false);
        RenderBounds = new AspectRef<RenderBounds>(renderBoundsLookup, entity, isReadOnly: false);
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new RoadVisualizerAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public RoadVisualizerAspect Set(LookupSlot<RoadVisualizerData> slot)
    {
        Data = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadVisualizerAspect Set(LookupSlot<RoadVisualizerData> slot, bool isReadOnly)
    {
        Data = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(LookupSlot<LocalTransform> slot)
    {
        LocalTransform = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadVisualizerAspect Set(LookupSlot<LocalTransform> slot, bool isReadOnly)
    {
        LocalTransform = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(LookupSlot<RuntimeUpdateableMesh> slot)
    {
        RuntimeUpdateableMesh = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadVisualizerAspect Set(LookupSlot<RuntimeUpdateableMesh> slot, bool isReadOnly)
    {
        RuntimeUpdateableMesh = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(LookupSlot<MaterialMeshInfo> slot)
    {
        MaterialMeshInfo = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadVisualizerAspect Set(LookupSlot<MaterialMeshInfo> slot, bool isReadOnly)
    {
        MaterialMeshInfo = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(LookupSlot<RenderBounds> slot)
    {
        RenderBounds = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadVisualizerAspect Set(LookupSlot<RenderBounds> slot, bool isReadOnly)
    {
        RenderBounds = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(ComponentLookup<RoadVisualizerData> lookup, bool isReadOnly = true)
    {
        Data = new AspectRef<RoadVisualizerData>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(ComponentLookup<LocalTransform> lookup, bool isReadOnly = true)
    {
        LocalTransform = new AspectRef<LocalTransform>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(ComponentLookup<RuntimeUpdateableMesh> lookup, bool isReadOnly = true)
    {
        RuntimeUpdateableMesh = new AspectRef<RuntimeUpdateableMesh>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(ComponentLookup<MaterialMeshInfo> lookup, bool isReadOnly = true)
    {
        MaterialMeshInfo = new AspectRef<MaterialMeshInfo>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadVisualizerAspect Set(ComponentLookup<RenderBounds> lookup, bool isReadOnly = true)
    {
        RenderBounds = new AspectRef<RenderBounds>(lookup, Entity, isReadOnly);
        return this;
    }

    // From IJobEntity Execute parameters.
    public RoadVisualizerAspect Set(RefRO<RoadVisualizerData> value)
    {
        Data = new AspectRef<RoadVisualizerData>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRW<RoadVisualizerData> value)
    {
        Data = new AspectRef<RoadVisualizerData>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRO<LocalTransform> value)
    {
        LocalTransform = new AspectRef<LocalTransform>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRW<LocalTransform> value)
    {
        LocalTransform = new AspectRef<LocalTransform>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRO<RuntimeUpdateableMesh> value)
    {
        RuntimeUpdateableMesh = new AspectRef<RuntimeUpdateableMesh>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRW<RuntimeUpdateableMesh> value)
    {
        RuntimeUpdateableMesh = new AspectRef<RuntimeUpdateableMesh>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRO<MaterialMeshInfo> value)
    {
        MaterialMeshInfo = new AspectRef<MaterialMeshInfo>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRW<MaterialMeshInfo> value)
    {
        MaterialMeshInfo = new AspectRef<MaterialMeshInfo>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRO<RenderBounds> value)
    {
        RenderBounds = new AspectRef<RenderBounds>(value);
        return this;
    }
    public RoadVisualizerAspect Set(RefRW<RenderBounds> value)
    {
        RenderBounds = new AspectRef<RenderBounds>(value);
        return this;
    }
    #endregion </auto-generated-lookup>
}
