using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;

public struct RoadPortData : IComponentData
{
    public RoadNodeEnt ParentNodeEnt;
}

public struct RoadPortInput : IBufferElementData
{
    public RoadLaneEnt RoadLaneEnt;
}

public struct RoadPortOutput : IBufferElementData
{
    public RoadLaneEnt RoadLaneEnt;
}

public struct RoadPortRemoveDuplicatesInOutBuffers : IComponentData, IEnableableComponent
{
}

public struct RoadPortAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    public struct Lookup
    {
        public LookupSlot<RoadPortData> RoadPortDataLookup;
        public LookupSlot<LocalTransform> LocalTransformLookup;
        public BufferSlot<RoadPortInput> RoadPortInputLookup;
        public BufferSlot<RoadPortOutput> RoadPortOutputLookup;
        public void Initialize(ref SystemState state)
        {
            RoadPortDataLookup.Initialize(ref state);
            LocalTransformLookup.Initialize(ref state);
            RoadPortInputLookup.Initialize(ref state);
            RoadPortOutputLookup.Initialize(ref state);
        }
        /// SystemBase / managed system variant.
        public void Initialize(ComponentSystemBase system)
        {
            RoadPortDataLookup.Initialize(system);
            LocalTransformLookup.Initialize(system);
            RoadPortInputLookup.Initialize(system);
            RoadPortOutputLookup.Initialize(system);
        }
        public void Update(ref SystemState state)
        {
            RoadPortDataLookup.Update(ref state);
            LocalTransformLookup.Update(ref state);
            RoadPortInputLookup.Update(ref state);
            RoadPortOutputLookup.Update(ref state);
        }
        public void Update(SystemBase system)
        {
            RoadPortDataLookup.Update(system);
            LocalTransformLookup.Update(system);
            RoadPortInputLookup.Update(system);
            RoadPortOutputLookup.Update(system);
        }
        public RoadPortAspect this[Entity e] => new RoadPortAspect
        {
            Entity = e,
            Data = RoadPortDataLookup.BindRW(e),
            LocalTransform = LocalTransformLookup.BindRef(e),
            Inputs = RoadPortInputLookup.Bind(e),
            Outputs = RoadPortOutputLookup.Bind(e)
        };
    }

    /// Main-thread construction without a cached Lookup: builds
    /// temporary lookups for this entity. Not usable inside jobs.
    /// (EntityManager cannot return RefRO/RefRW for an entity.)
    public RoadPortAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadPortDataLookup = state.GetComponentLookup<RoadPortData>(isReadOnly: false);
        var localTransformLookup = state.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var roadPortInputLookup = state.GetBufferLookup<RoadPortInput>(isReadOnly: false);
        var roadPortOutputLookup = state.GetBufferLookup<RoadPortOutput>(isReadOnly: false);
        Data = roadPortDataLookup.GetRefRW(entity);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        Inputs = roadPortInputLookup[entity];
        Outputs = roadPortOutputLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadPortAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadPortDataLookup = system.GetComponentLookup<RoadPortData>(isReadOnly: false);
        var localTransformLookup = system.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var roadPortInputLookup = system.GetBufferLookup<RoadPortInput>(isReadOnly: false);
        var roadPortOutputLookup = system.GetBufferLookup<RoadPortOutput>(isReadOnly: false);
        Data = roadPortDataLookup.GetRefRW(entity);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        Inputs = roadPortInputLookup[entity];
        Outputs = roadPortOutputLookup[entity];
    }

    /// Builds the aspect from IJobEntity Execute parameters — no
    /// Lookup needed. Pass default for fields this job does not
    /// iterate; unbound fields simply read as invalid. Tolerant
    /// (AspectRef) fields take an RO and an RW parameter: pass just
    /// the RW one for full read+write, or just the RO one for reads.
    public static RoadPortAspect Create(Entity entity,
        RefRW<RoadPortData> data = default,
        RefRO<LocalTransform> localTransformRO = default,
        RefRW<LocalTransform> localTransformRW = default,
        DynamicBuffer<RoadPortInput> inputs = default,
        DynamicBuffer<RoadPortOutput> outputs = default)
    {
        return new RoadPortAspect
        {
            Entity = entity,
            Data = data,
            LocalTransform = new AspectRef<LocalTransform>(localTransformRO, localTransformRW),
            Inputs = inputs,
            Outputs = outputs
        };
    }
    #endregion </auto-generated-lookup>
    public Entity Entity;
    private RefRW<RoadPortData> Data;
    private AspectRef<LocalTransform> LocalTransform;
    private DynamicBuffer<RoadPortInput> Inputs;
    private DynamicBuffer<RoadPortOutput> Outputs;

    public float3 Position
    {
        get => LocalTransform.ValueRO.Position;
        set => LocalTransform.ValueRW.Position = value;
    }
    public RoadNodeEnt Parent
    {
        get => Data.ValueRO.ParentNodeEnt;
        set => Data.ValueRW.ParentNodeEnt = value;
    }

    public bool AddInputLane(RoadLaneEnt roadLane)
    {
        // find duplicates
        for (int i = 0; i < Inputs.Length; i++)
            if (Inputs[i].RoadLaneEnt == roadLane)
                return false;
        Inputs.Add(new RoadPortInput { RoadLaneEnt = roadLane });
        return true;
    }

    public bool AddOutputLane(RoadLaneEnt roadLane)
    {
        // find duplicates
        for (int i = 0; i < Inputs.Length; i++)
            if (Outputs[i].RoadLaneEnt == roadLane)
                return false;
        Outputs.Add(new RoadPortOutput { RoadLaneEnt = roadLane });
        return true;
    }

}