using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;

public struct RoadPortData : IComponentData
{
    public RoadNodeEnt ParentNodeEnt;
}

public struct RoadPortInput : IBufferElementData
{
    public RoadLaneEnt RoadLaneEnt;
}

public struct RoadPortOutput : IBufferElementData
{
    public RoadLaneEnt RoadLaneEnt;
}

public struct RoadPortRemoveDuplicatesInOutBuffers : IComponentData, IEnableableComponent
{
}

public struct RoadPortAspect : IAspect
{
    #region <auto-generated-lookup> do not edit; regenerated by GenerateAspectLookups
    /// Entity-only: bind fields afterwards with chained Set(...).
    public RoadPortAspect(Entity entity)
    {
        this = default;
        Entity = entity;
    }

    /// Binds every field through temporary lookups. Main-thread use;
    /// prefer declared slots + chained Set(...) inside systems.
    public RoadPortAspect(ref SystemState state, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadPortDataLookup = state.GetComponentLookup<RoadPortData>(isReadOnly: false);
        var localTransformLookup = state.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var roadPortInputLookup = state.GetBufferLookup<RoadPortInput>(isReadOnly: false);
        var roadPortOutputLookup = state.GetBufferLookup<RoadPortOutput>(isReadOnly: false);
        Data = new AspectRef<RoadPortData>(roadPortDataLookup, entity, isReadOnly: false);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        Inputs = roadPortInputLookup[entity];
        Outputs = roadPortOutputLookup[entity];
    }

    /// SystemBase / managed system variant.
    public RoadPortAspect(SystemBase system, Entity entity)
    {
        this = default;
        Entity = entity;
        var roadPortDataLookup = system.GetComponentLookup<RoadPortData>(isReadOnly: false);
        var localTransformLookup = system.GetComponentLookup<LocalTransform>(isReadOnly: false);
        var roadPortInputLookup = system.GetBufferLookup<RoadPortInput>(isReadOnly: false);
        var roadPortOutputLookup = system.GetBufferLookup<RoadPortOutput>(isReadOnly: false);
        Data = new AspectRef<RoadPortData>(roadPortDataLookup, entity, isReadOnly: false);
        LocalTransform = new AspectRef<LocalTransform>(localTransformLookup, entity, isReadOnly: false);
        Inputs = roadPortInputLookup[entity];
        Outputs = roadPortOutputLookup[entity];
    }

    // Set(...) overloads. Each returns the aspect, so calls chain:
    //   new RoadPortAspect(e).Set(slotA).Set(bufferB);
    // Statement form works too — Set mutates this and returns a copy.

    public RoadPortAspect Set(LookupSlot<RoadPortData> slot)
    {
        Data = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadPortAspect Set(LookupSlot<RoadPortData> slot, bool isReadOnly)
    {
        Data = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadPortAspect Set(LookupSlot<LocalTransform> slot)
    {
        LocalTransform = slot.BindRef(Entity);
        return this;
    }
    /// Explicit mode: isReadOnly: true downgrades a read-write
    /// slot; isReadOnly: false on a read-only slot throws.
    public RoadPortAspect Set(LookupSlot<LocalTransform> slot, bool isReadOnly)
    {
        LocalTransform = slot.BindRef(Entity, isReadOnly);
        return this;
    }

    public RoadPortAspect Set(BufferSlot<RoadPortInput> slot)
    {
        Inputs = slot.Bind(Entity);
        return this;
    }

    public RoadPortAspect Set(BufferSlot<RoadPortOutput> slot)
    {
        Outputs = slot.Bind(Entity);
        return this;
    }

    public RoadPortAspect Set(ComponentLookup<RoadPortData> lookup, bool isReadOnly)
    {
        Data = new AspectRef<RoadPortData>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadPortAspect Set(ComponentLookup<LocalTransform> lookup, bool isReadOnly)
    {
        LocalTransform = new AspectRef<LocalTransform>(lookup, Entity, isReadOnly);
        return this;
    }

    public RoadPortAspect Set(BufferLookup<RoadPortInput> lookup)
    {
        Inputs = lookup[Entity];
        return this;
    }

    public RoadPortAspect Set(BufferLookup<RoadPortOutput> lookup)
    {
        Outputs = lookup[Entity];
        return this;
    }

    // From IJobEntity Execute parameters.
    public RoadPortAspect Set(RefRO<RoadPortData> value)
    {
        Data = new AspectRef<RoadPortData>(value);
        return this;
    }
    public RoadPortAspect Set(RefRW<RoadPortData> value)
    {
        Data = new AspectRef<RoadPortData>(value);
        return this;
    }
    public RoadPortAspect Set(RefRO<LocalTransform> value)
    {
        LocalTransform = new AspectRef<LocalTransform>(value);
        return this;
    }
    public RoadPortAspect Set(RefRW<LocalTransform> value)
    {
        LocalTransform = new AspectRef<LocalTransform>(value);
        return this;
    }
    public RoadPortAspect Set(DynamicBuffer<RoadPortInput> buffer)
    {
        Inputs = buffer;
        return this;
    }
    public RoadPortAspect Set(DynamicBuffer<RoadPortOutput> buffer)
    {
        Outputs = buffer;
        return this;
    }
    #endregion </auto-generated-lookup>
    public Entity Entity;
    private AspectRef<RoadPortData> Data;
    private AspectRef<LocalTransform> LocalTransform;
    private DynamicBuffer<RoadPortInput> Inputs;
    private DynamicBuffer<RoadPortOutput> Outputs;

    public float3 Position
    {
        get => LocalTransform.ValueRO.Position;
        set => LocalTransform.ValueRW.Position = value;
    }
    public RoadNodeEnt Parent
    {
        get => Data.ValueRO.ParentNodeEnt;
        set => Data.ValueRW.ParentNodeEnt = value;
    }

    public bool AddInputLane(RoadLaneEnt roadLane)
    {
        // find duplicates
        for (int i = 0; i < Inputs.Length; i++)
            if (Inputs[i].RoadLaneEnt == roadLane)
                return false;
        Inputs.Add(new RoadPortInput { RoadLaneEnt = roadLane });
        return true;
    }

    public bool AddOutputLane(RoadLaneEnt roadLane)
    {
        // find duplicates
        for (int i = 0; i < Inputs.Length; i++)
            if (Outputs[i].RoadLaneEnt == roadLane)
                return false;
        Outputs.Add(new RoadPortOutput { RoadLaneEnt = roadLane });
        return true;
    }

}